services:
  - type: web
    name: surveycto-to-github
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GITHUB_APP_ID
        value: "1363212"
      - key: GITHUB_INSTALLATION_ID
        value: "69668918"
      - key: GITHUB_REPO
        value: "schneideraxel/ideal-automation-test"